/**
 * @wizz/contracts — the shared vocabulary between the wizz.video gateway
 * (services/gateway), the public SPA, and the admin SPA (both apps/web build
 * targets). Pre-committed BEFORE the parallel build waves (the zero-redo
 * pattern): builders implement against these shapes and do not edit this file
 * without orchestrator sign-off.
 *
 * Dependency-free on purpose: plain types + constants only, so the gateway
 * (node) and the web app (vite) both import it with zero build friction.
 * Runtime validation lives with each consumer (the gateway validates request
 * bodies; the client validates preset payloads via its existing
 * migrateLabSettings-style salvagers).
 *
 * The HTTP surface these types ride on is specified in docs/wizz-contracts.md
 * (gitignored ops doc — read it from disk). Wire-shape rule: JSON everywhere,
 * dates as ISO-8601 UTC strings, money as USD numbers (null = unknown, never
 * "free").
 */

/* ────────────────────────────── errors ────────────────────────────── */

/**
 * Every non-2xx gateway response carries this envelope. `code` is the
 * machine-readable contract the client maps to friendly UI; `message` is a
 * human-readable English sentence safe to show in admin surfaces (public UI
 * writes its own copy per code).
 */
export interface WizzApiError {
  error: {
    code: WizzErrorCode;
    message: string;
    /** quota_exceeded only: which bucket ran dry. */
    category?: QuotaCategory;
    /** quota_exceeded only: ISO time the daily window resets (next UTC midnight). */
    resetsAt?: string;
    /** rate_limited only: seconds until retry is sensible. */
    retryAfterS?: number;
  };
}

export const WIZZ_ERROR_CODES = [
  "auth_required", // 401 — no/invalid session cookie
  "invalid_credentials", // 401 — login failed
  "invite_invalid", // 400 — unknown, expired, exhausted, or disabled invite
  "email_taken", // 400 — signup with an existing email
  "weak_password", // 400 — under 8 chars
  "bad_request", // 400 — malformed body / missing fields / bad category header
  "bad_origin", // 403 — Origin header missing/mismatched on a mutating route
  "admin_only", // 403 — admin route hit on the public listener
  "forbidden_path", // 403 — proxy path outside the provider whitelist
  "account_disabled", // 403 — user flagged disabled by the admin
  "not_found", // 404
  "quota_exceeded", // 402 — daily category budget spent (carries category + resetsAt)
  "payload_too_large", // 413 — body over the per-provider cap
  "rate_limited", // 429 — per-user or per-IP window exceeded (carries retryAfterS)
  "upstream_error", // 502 — provider returned 5xx / unreachable / non-JSON
  "kill_switch", // 503 — admin disabled all proxying ("the director is taking a break")
] as const;
export type WizzErrorCode = (typeof WIZZ_ERROR_CODES)[number];

/** HTTP status the gateway MUST use per code (tests assert this mapping). */
export const WIZZ_ERROR_STATUS: Record<WizzErrorCode, number> = {
  auth_required: 401,
  invalid_credentials: 401,
  invite_invalid: 400,
  email_taken: 400,
  weak_password: 400,
  bad_request: 400,
  bad_origin: 403,
  admin_only: 403,
  forbidden_path: 403,
  account_disabled: 403,
  not_found: 404,
  quota_exceeded: 402,
  payload_too_large: 413,
  rate_limited: 429,
  upstream_error: 502,
  kill_switch: 503,
};

/* ────────────────────────────── auth ────────────────────────────── */

/** What the client is allowed to know about a user (public + admin SPAs). */
export interface PublicUser {
  id: string;
  email: string;
  createdAt: string;
}

/** Admin view: PublicUser plus operational fields. */
export interface AdminUser extends PublicUser {
  disabled: boolean;
  /** Sparse per-category overrides layered over GlobalSettings.defaultQuotas. */
  quotaOverrides: Partial<QuotaLimits> | null;
  lastSeenAt: string | null;
  /** Which invite admitted them (null for pre-invite/seed accounts). */
  inviteId: string | null;
}

export interface SignupRequest {
  inviteCode: string;
  email: string;
  password: string; // ≥ WIZZ_PASSWORD_MIN_LENGTH chars
}
export interface LoginRequest {
  email: string;
  password: string;
}
/** 200 body for signup, login, and GET session. */
export interface SessionResponse {
  user: PublicUser;
}

export const WIZZ_PASSWORD_MIN_LENGTH = 8;
/** Session cookie: httpOnly, Secure, SameSite=Lax, Path=/. */
export const WIZZ_SESSION_COOKIE = "wizz_session";
export const WIZZ_SESSION_TTL_DAYS = 30;

export interface InviteCode {
  id: string;
  code: string;
  maxUses: number;
  usedCount: number;
  expiresAt: string | null;
  disabled: boolean;
  createdAt: string;
  /** Admin-facing label ("launch batch #1"). */
  note: string | null;
}

/* ────────────────────────────── quotas ────────────────────────────── */

/**
 * The four billable categories. Daily windows reset at UTC midnight.
 * v1 ships with every default limit = null (unlimited) — the engine exists,
 * the ceilings are a settings change, not a deploy.
 */
export const QUOTA_CATEGORIES = [
  "directorTokens", // openai/openrouter chat tokens (prompt+completion), category "director"
  "sunoGens", // suno POST /generate calls, category "music"
  "cloudCaptionFrames", // image parts in chat bodies, category "caption" (public v1: off via preset)
  "sttSeconds", // groq billed seconds (min 10s per request), category "stt"
] as const;
export type QuotaCategory = (typeof QUOTA_CATEGORIES)[number];

/** null = unlimited (first-class, the v1 default for every category). */
export type QuotaLimits = Record<QuotaCategory, number | null>;

export const UNLIMITED_QUOTAS: QuotaLimits = {
  directorTokens: null,
  sunoGens: null,
  cloudCaptionFrames: null,
  sttSeconds: null,
};

/** GET /api/quota response — the signed-in user's remaining budget. */
export interface QuotaStatus {
  categories: Record<
    QuotaCategory,
    {
      limit: number | null; // effective (override ?? default); null = unlimited
      used: number; // today's consumption (UTC window)
      remaining: number | null; // null when unlimited
    }
  >;
  resetsAt: string; // next UTC midnight, ISO
  killSwitch: boolean;
}

/* ─────────────────────────── proxy metering ─────────────────────────── */

/**
 * Every /api/proxy/* call declares its quota category via this header.
 * The gateway rejects a missing/invalid value, or a category the provider
 * cannot bill (e.g. stt on openai), with 400 bad_request. The service layer
 * sets it once per call site — this is part of the "credentials + error
 * handling" client change, not URL surgery.
 */
export const WIZZ_CATEGORY_HEADER = "x-wizz-category";

export const USAGE_CATEGORIES = ["director", "caption", "stt", "music"] as const;
export type UsageCategory = (typeof USAGE_CATEGORIES)[number];

export const USAGE_PROVIDERS = ["openai", "openrouter", "groq", "suno"] as const;
export type UsageProvider = (typeof USAGE_PROVIDERS)[number];

/** Which categories each provider may bill (gateway validates the header against this). */
export const PROVIDER_CATEGORIES: Record<UsageProvider, readonly UsageCategory[]> = {
  openai: ["director", "caption"],
  openrouter: ["director", "caption"],
  groq: ["stt"],
  suno: ["music"],
};

/** Which quota bucket a metered category drains. */
export const CATEGORY_QUOTA: Record<UsageCategory, QuotaCategory> = {
  director: "directorTokens",
  caption: "cloudCaptionFrames",
  stt: "sttSeconds",
  music: "sunoGens",
};

/**
 * Upstream bases + path whitelists. Anything not listed → 403 forbidden_path
 * (no open-proxy behavior; WS-F fuzzes this). Paths are matched after the
 * provider prefix: /api/proxy/openai/chat/completions → "chat/completions".
 * record-info GET polls are session-checked but never decrement a quota.
 */
export const PROXY_UPSTREAMS: Record<
  UsageProvider,
  { base: string; allow: readonly { method: "GET" | "POST"; path: string }[] }
> = {
  openai: {
    base: "https://api.openai.com/v1",
    allow: [
      { method: "POST", path: "chat/completions" },
      { method: "GET", path: "models" }, // health checks only
    ],
  },
  openrouter: {
    base: "https://openrouter.ai/api/v1",
    allow: [{ method: "POST", path: "chat/completions" }],
  },
  groq: {
    base: "https://api.groq.com/openai/v1",
    allow: [{ method: "POST", path: "audio/transcriptions" }],
  },
  suno: {
    base: "https://api.sunoapi.org/api/v1",
    allow: [
      { method: "POST", path: "generate" },
      { method: "GET", path: "generate/record-info" },
    ],
  },
};

/** Per-provider request-body caps the gateway enforces (nginx mirrors them). */
export const PROXY_BODY_LIMIT_BYTES: Record<UsageProvider, number> = {
  openai: 4 * 1024 * 1024, // text-only chat on the public path; caption frames ride openrouter/openai on admin
  openrouter: 16 * 1024 * 1024, // caption batches carry base64 frames
  groq: 64 * 1024 * 1024, // opus ~11MB/h, WAV fallback ~19MB/600s chunk
  suno: 256 * 1024,
};

/**
 * One row per proxied call (success OR failure), the metering ground truth.
 * Parsing mirrors the client's cost-truth semantics exactly:
 * - tokens from response.usage (prompt/completion/prompt_tokens_details.cached_tokens)
 * - actualCostUSD: OpenRouter usage.cost verbatim when present; Groq
 *   billedSeconds × $0.04/3600; OpenAI/Suno null (null = unknown, never free)
 * - groq seconds: max(response duration, 10) per request
 * - suno units: 1 per accepted POST /generate
 */
export interface UsageEvent {
  id: string;
  userId: string;
  provider: UsageProvider;
  category: UsageCategory;
  model: string | null;
  promptTokens: number | null;
  completionTokens: number | null;
  cachedTokens: number | null;
  frames: number | null; // caption image parts counted from the request body
  seconds: number | null; // groq billed seconds
  units: number | null; // suno generations
  actualCostUSD: number | null;
  upstreamStatus: number;
  at: string;
}

/* ──────────────────────── global settings (admin) ──────────────────────── */

/**
 * The admin System section edits exactly this object (PUT /api/admin/settings).
 * Changing any of it is a DB write, not a deploy.
 */
export interface GlobalSettings {
  /** Per-category daily defaults; per-user overrides layer on top. All null in v1. */
  defaultQuotas: QuotaLimits;
  /** Client-enforced per-generate footage ceiling (from the active preset fetch). */
  footageCap: FootageCap;
  /** true → every /api/proxy/* call 503s with code kill_switch. */
  killSwitch: boolean;
  /** Which PublishedPreset the public app receives; null → DEFAULT_PUBLISHED_PRESET. */
  activePresetId: string | null;
  /** v1: true. Flipping to false opens signup without codes (not planned). */
  inviteRequired: boolean;
}

export interface FootageCap {
  maxClips: number;
  maxTotalSeconds: number;
}

export const DEFAULT_GLOBAL_SETTINGS: GlobalSettings = {
  defaultQuotas: UNLIMITED_QUOTAS,
  footageCap: { maxClips: 25, maxTotalSeconds: 3600 }, // vacation-scale is the product
  killSwitch: false,
  activePresetId: null,
  inviteRequired: true,
};

/* ─────────────────────────── published preset ─────────────────────────── */

/**
 * The public product's entire settings surface, admin-authored. The public
 * app fetches the active preset at load (GET /api/preset) and constructs
 * director runs exactly as the lab does; every dial the public cannot see is
 * locked in here.
 *
 * `labSettings` is deliberately `unknown` at the wire level: it is a
 * LabSettings-shaped bundle (apps/web/src/pages/lab/lab-settings.ts) and the
 * client runs it through migrateLabSettings — the existing per-field salvager
 * — so a stale preset can never brick the public app.
 */
export interface PublishedPreset {
  id: string;
  name: string;
  /** Bumped on every publish of this preset id. */
  version: number;
  publishedAt: string | null;
  /** StylePreset ids from @openreel/core style-presets.ts, in display order. */
  styleWhitelist: string[];
  /** Director model id, e.g. "gpt-5.4-mini" (slash-prefixed ids route to openrouter). */
  directorModel: string;
  promptMode: "full" | "candidates";
  /**
   * Which transcript the director reads. Stays "local" until the WS-E
   * VAD-gate-uploads fast-follow lands (cloud whisper hallucinates on
   * non-speech and those hallucinations would feed the director).
   */
  transcriptSource: "local" | "cloud";
  /** Show the cloud-STT toggle and default it on (Groq transcription runs + is metered). */
  cloudSTTDefaultOn: boolean;
  /** Cloud caption enhancement for public runs (v1: false — local FastVLM only). */
  cloudCaptionsEnabled: boolean;
  /** Music toggle available (Suno). */
  musicEnabled: boolean;
  /** Duration chips, seconds, in display order. */
  targetDurationChoicesS: number[];
  allowCustomDuration: boolean;
  minTargetDurationS: number;
  maxTargetDurationS: number;
  /** LabSettings-shaped bundle (selector config, local whisper model, VAD) — see doc above. */
  labSettings: unknown;
}

/**
 * The wireframe's six style cards, mapped to existing style-presets.ts ids
 * ("Rhythm montage" = beat-montage). The admin Presets section can expand
 * this from the full 11-voice catalog later.
 */
export const DEFAULT_STYLE_WHITELIST = [
  "atmospheric",
  "energetic-vlog",
  "cinematic",
  "memory-film",
  "beat-montage",
  "social-teaser",
] as const;

/** Fallback when no preset row is active — also the seed the admin UI edits first. */
export const DEFAULT_PUBLISHED_PRESET: PublishedPreset = {
  id: "default",
  name: "wizz launch preset",
  version: 1,
  publishedAt: null,
  styleWhitelist: [...DEFAULT_STYLE_WHITELIST],
  directorModel: "gpt-5.4-mini",
  promptMode: "candidates",
  transcriptSource: "local",
  cloudSTTDefaultOn: true,
  cloudCaptionsEnabled: false,
  musicEnabled: true,
  targetDurationChoicesS: [30, 60, 90, 180],
  allowCustomDuration: true,
  minTargetDurationS: 15,
  maxTargetDurationS: 600,
  labSettings: null, // null → client uses defaultLabSettings()
};

/** GET /api/preset response. */
export interface PresetResponse {
  preset: PublishedPreset;
  footageCap: FootageCap;
}

/* ────────────────────────────── telemetry ────────────────────────────── */

/**
 * POST /api/telemetry — client events the admin can see. No pixels, no
 * transcripts, no filenames. 204 on accept; fire-and-forget client-side.
 */
export const TELEMETRY_TYPES = [
  "session_start",
  "analyze_started",
  "analyze_completed",
  "analyze_failed",
  "generate_started",
  "generate_succeeded",
  "generate_failed",
  "refine_started",
  "export_started",
  "export_completed",
  "export_failed",
  "editor_opened",
] as const;
export type TelemetryType = (typeof TELEMETRY_TYPES)[number];

export interface TelemetryEventBody {
  type: TelemetryType;
  /** Coarse numbers only (clipCount, totalDurationS, durationMs, errorCode…). */
  data?: Record<string, string | number | boolean | null>;
}

/* ─────────────────────────── admin API shapes ─────────────────────────── */

export interface AdminUserSummary extends AdminUser {
  /** Lifetime + today rollups for the Users list. */
  usage: {
    today: Partial<Record<QuotaCategory, number>>;
    total: Partial<Record<QuotaCategory, number>>;
    knownCostUSD: number; // Σ actualCostUSD where reported (a floor, not the bill)
    events: number;
  };
}

export interface UsageRollupRow {
  /** Grouping key values present per requested groupBy (day/user/provider/model/category). */
  day?: string; // "2026-07-07" (UTC)
  userId?: string;
  email?: string;
  provider?: UsageProvider;
  model?: string | null;
  category?: UsageCategory;
  events: number;
  promptTokens: number;
  completionTokens: number;
  cachedTokens: number;
  frames: number;
  seconds: number;
  units: number;
  /** Exact-$ sum over rows that reported cost; null when none did. */
  knownCostUSD: number | null;
  /** How many of `events` carried actualCostUSD (cost-truth: all-or-null honesty). */
  costedEvents: number;
}

export interface AdminHealth {
  ok: boolean;
  version: string; // gateway build/commit
  uptimeS: number;
  db: { ok: boolean; sizeBytes: number; users: number; usageEvents: number };
  killSwitch: boolean;
}

/* ─────────────────────── generate-flow state machine ─────────────────────── */

/**
 * The public generate flow (WS-D implements, WS-E wires). One state atom;
 * transitions are the ONLY way scenes change. The bench is not a wizard:
 * `bench` covers both analyzing and ready (per-clip statuses live beside it),
 * and the direction panel stays interactive throughout.
 */
export type GenerateFlowState =
  | { name: "gate-unsupported" } // no WebGPU/wrong browser — friendly explainer
  | { name: "needs-auth" }
  | { name: "studio-empty"; firstVisit: boolean } // firstVisit → model prep strip
  | { name: "studio-restore-offer"; clipCount: number; label: string } // "Reload Tuesday's footage?"
  | { name: "bench"; allReady: boolean } // clips analyzing/ready; generate arms when allReady
  | { name: "directing"; sinceRefine: boolean }
  | { name: "screening"; rendering: boolean } // render overlay is a screening sub-state
  | { name: "service-away"; reason: "kill_switch" | "upstream_error" } // "director taking a break"
  | { name: "quota-exceeded"; category: QuotaCategory; resetsAt: string };

export type GenerateFlowEvent =
  | { type: "SESSION_OK" }
  | { type: "SESSION_MISSING" }
  | { type: "UNSUPPORTED_BROWSER" }
  | { type: "RESTORE_AVAILABLE"; clipCount: number; label: string }
  | { type: "RESTORE_ACCEPTED" }
  | { type: "RESTORE_DECLINED" }
  | { type: "CLIPS_ADDED" }
  | { type: "ALL_CLIPS_READY" }
  | { type: "CLIPS_CHANGED" } // add/remove/retry while on the bench
  | { type: "GENERATE" }
  | { type: "DIRECTOR_DONE" }
  | { type: "DIRECTOR_CANCELLED" }
  | { type: "DIRECTOR_FAILED"; code: WizzErrorCode }
  | { type: "REFINE" }
  | { type: "CHANGE_SETUP" }
  | { type: "RENDER" }
  | { type: "RENDER_DONE" }
  | { type: "RENDER_CANCELLED" }
  | { type: "RETRY" }; // from service-away / quota-exceeded back to bench

/* ─────────────────────────── build targets ─────────────────────────── */

/**
 * `VITE_APP_TARGET` selects which app main.tsx boots. Absent (today's dev
 * default) = "admin" — the full existing app plus the admin shell, so nothing
 * about the current workflow changes. "public" boots the wizz.video product
 * and MUST tree-shake every lab/experiments/perf module out of the bundle
 * (verified by grepping dist for lab-only markers, not by hidden routes).
 */
export type AppTarget = "public" | "admin";

/** Public SPA path routes (served under /app with nginx html fallback). */
export const PUBLIC_ROUTES = {
  landing: "/", // static page, not the SPA
  app: "/app", // redirects to /app/generate
  auth: "/app/auth",
  generate: "/app/generate",
  editor: "/app/editor",
} as const;

/** Admin SPA keeps today's hash routing; new shell sections beside #/lab. */
export const ADMIN_ROUTES = {
  lab: "#/lab",
  users: "#/users",
  usage: "#/usage",
  presets: "#/presets",
  system: "#/system",
} as const;

/* ─────────────────────────── gateway runtime ─────────────────────────── */

/**
 * Two listeners, one app: nginx's public vhost proxies to PORT_PUBLIC where
 * /api/admin/* answers 403 admin_only; the tailnet vhost proxies to
 * PORT_ADMIN where admin routes are live. "Arrived on the tailnet" is thus a
 * port-binding fact, not a header the public could forge.
 */
export const WIZZ_GATEWAY_PORT_PUBLIC = 8792;
export const WIZZ_GATEWAY_PORT_ADMIN = 8793;

/** Environment contract for /etc/wizz/gateway.env (systemd EnvironmentFile). */
export const WIZZ_ENV_KEYS = [
  "WIZZ_DB_PATH", // /var/lib/wizz/gateway.db
  "WIZZ_PORT_PUBLIC", // default 8792
  "WIZZ_PORT_ADMIN", // default 8793
  "WIZZ_PUBLIC_ORIGIN", // https://wizz.video
  "WIZZ_ADMIN_ORIGIN", // https://wizz.pbrain.dev
  "WIZZ_OPENAI_KEY",
  "WIZZ_OPENROUTER_KEY",
  "WIZZ_GROQ_KEY",
  "WIZZ_SUNO_KEY",
] as const;

/** Per-user and per-IP sliding-window limits on /api/proxy/* (public listener only). */
export const RATE_LIMITS = {
  perUserPerMinute: 60,
  perIpPerMinute: 120,
  telemetryPerUserPerMinute: 120,
} as const;
